<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * alcoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class alcoolRepository extends \Doctrine\ORM\EntityRepository
{
}
