<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * goutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class goutRepository extends \Doctrine\ORM\EntityRepository
{
}
